language: node_js
node_js:
  - "6"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
  mongodb: '~1.3.6'
services:
- mongodb
before_script: 
- bower install"
script:
- npm run lint:ci
- npm test
- npm run build:prod
